In [ ]:
import torch
import pandas as pd
import matplotlib as plt

#Scalar

**In Python, a scalar is a single value (not a collection) that represents one quantity — such as a number, a single character, or a boolean.
Scalars are the simplest data types and are the building blocks for more complex structures like lists, arrays, or dictionaries**

In [ ]:
#scalar
scalar=torch.tensor(4)
scalar

tensor(4)

In [ ]:
scalar.ndim
#scalar has no dimension

0

In [ ]:
scalar.item()
#you get back the python int

4

In [ ]:
vector=torch.tensor([5,6])
vector

tensor([5, 6])

In [ ]:
vector.ndim
#(number of square brakects)

1

In [ ]:
vector.shape
'''ndim → How many dimensions the tensor has.
   shape → Size in each dimension.'''

'ndim → How many dimensions the tensor has.\n   shape → Size in each dimension.'

In [ ]:
print(vector.tolist())
vector[0].item()

[5, 6]


5

In [ ]:
#Matrix
matrix=torch.tensor([[3,4],[8,2]])
matrix

tensor([[3, 4],
        [8, 2]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[0][0]

tensor(3)

In [ ]:
#tensor
Tensor=torch.tensor([[[6,7],[5,8],[2,9]]])
Tensor

tensor([[[6, 7],
         [5, 8],
         [2, 9]]])

In [ ]:
Tensor.ndim

3

In [ ]:
#dont get confused
Tensor.shape

torch.Size([1, 3, 2])

In [ ]:
Tensor[0][2][0]

tensor(2)

#Random tensors
Random tensors are imp because the way many neural network learn is that they start with tensors full
of random numbers and then adjust those numbers to better represent the data.


In [ ]:
#Random tensor
random_tensor=torch.rand(1,3,2)
random_tensor

tensor([[[0.2696, 0.4414],
         [0.2969, 0.8317],
         [0.1053, 0.2695]]])

In [ ]:
#tensor with all zeros
zeros=torch.zeros(3,2)
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
#tensor with all one
ones=torch.ones(3,2)
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
ones.dtype
#by default the data type is float32

torch.float32

#Create a range of tensors and tensors-like

In [ ]:
one_to_ten=torch.arange(start=1,step=1,end=11)#order doesnt matter
one_to_ten



tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#create tensor-like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#Tensor datatype
tensor data type is one of the 3 big errors you'll run into

1.tensor not right datatype(most of the time it runs without error)

2.not right shape

3.not on right device

In [ ]:
#Float 32 tensor
float_32_tensor=torch.tensor([3.587,6.756],
                             device=None,
                             dtype=None,
                             requires_grad=False)#whether or not to track gradients with this tensor operation
float_32_tensor


tensor([3.5870, 6.7560])

In [ ]:
#changing datatype
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.5879, 6.7578], dtype=torch.float16)

tensor.shape

tensor.dtype

tensor.device

In [ ]:
some_tensor=torch.rand([4,5])
some_tensor

tensor([[0.3588, 0.1994, 0.5472, 0.0062, 0.9516],
        [0.0753, 0.8860, 0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547, 0.3423, 0.6343],
        [0.3644, 0.7104, 0.9464, 0.7890, 0.2814]])

In [ ]:
some_tensor.device,some_tensor.shape,some_tensor.dtype

(device(type='cpu'), torch.Size([4, 5]), torch.float32)

In [ ]:
#addition
tensor=torch.tensor([1,2,3])
tensor+10  #torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
#multipliction(element wise)
tensor*10  #torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
#division
tensor=tensor*10
print(tensor/10)

tensor([1., 2., 3.])


In [ ]:
#subtraction
tensor-1

tensor([ 9, 19, 29])

In [ ]:
#matrix multiplication
torch.matmul(tensor,tensor) #we can also use tensor @ tensor
                            #or torch.mm(tensor,tensor)

tensor(1400)

In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 493 µs, sys: 0 ns, total: 493 µs
Wall time: 356 µs


tensor(1400)

In [ ]:
#transpose
some_tensor.T

tensor([[0.3588, 0.0753, 0.5779, 0.3644],
        [0.1994, 0.8860, 0.9040, 0.7104],
        [0.5472, 0.5832, 0.5547, 0.9464],
        [0.0062, 0.3376, 0.3423, 0.7890],
        [0.9516, 0.8090, 0.6343, 0.2814]])

#Min,Max,Mean,Sum

In [ ]:
x=torch.rand([1,3])
x

tensor([[0.7886, 0.5895, 0.7539]])

In [ ]:
torch.min(x)

tensor(0.5895)

In [ ]:
torch.max(x)

tensor(0.7886)

In [ ]:
torch.mean(x),x.mean()

(tensor(0.7107), tensor(0.7107))

In [ ]:
torch.sum(x),x.sum()

(tensor(2.1320), tensor(2.1320))

Finding position of min and max

In [ ]:
x.argmin()

tensor(1)

In [ ]:
x.argmax()

tensor(0)

Reshaping,stacking,squeezing and ubsqueezing

In [ ]:
x=torch.arange(0,100,10)
x,x.shape

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.Size([10]))

In [ ]:
x.reshape(2,5)

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [ ]:
#if i use view, both z and x share same memory
z=x.view(2,5)
z

tensor([[ 0, 10, 20, 30, 40],
        [50, 60, 70, 80, 90]])

In [ ]:
#stack tensor on top of each other
x_stacked=torch.stack([x,x,x],dim=0)
x_stacked

tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90],
        [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [ ]:
x=torch.rand([1,1,10])
x,x.shape

(tensor([[[0.1952, 0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071, 0.6581,
           0.4913, 0.8913]]]),
 torch.Size([1, 1, 10]))

In [ ]:
#torch.squeeze()-removes all single dimensions from a target tensor
s=x.squeeze()
s

tensor([0.1952, 0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071, 0.6581, 0.4913,
        0.8913])

In [ ]:
s.shape

torch.Size([10])

In [ ]:
# torch.unsqueeze()-adds a single dimension to a target tensor at a specific dim
u=s.unsqueeze(dim=1)
u,u.shape

(tensor([[0.1952],
         [0.0050],
         [0.3068],
         [0.1165],
         [0.9103],
         [0.6440],
         [0.7071],
         [0.6581],
         [0.4913],
         [0.8913]]),
 torch.Size([10, 1]))

In [ ]:
#torch.permute-rearrange the dimensions of a target tensor in a specified order
image=torch.rand(224,224,3)
image.shape

torch.Size([224, 224, 3])

In [ ]:
p=image.permute(1,0,2)
p.shape

torch.Size([224, 224, 3])

#Pytorch and Numpy

In [ ]:
 import torch
 import numpy as np
a=np.arange(4,9)
tensor=torch.from_numpy(a) # use torch.from_numpy
a,tensor
#memory is not shared between a and tensor

(array([4, 5, 6, 7, 8]), tensor([4, 5, 6, 7, 8]))

In [ ]:
#tensor to numpy
tensor=torch.rand(10)
n=tensor.numpy()
tensor,n

(tensor([0.5510, 0.2485, 0.8518, 0.0963, 0.1338, 0.2741, 0.6142, 0.8973, 0.3629,
         0.1748]),
 array([0.55097604, 0.248523  , 0.85175765, 0.09626013, 0.1337679 ,
        0.27408642, 0.61418384, 0.8973308 , 0.36289257, 0.17478275],
       dtype=float32))

Reproducible tensors

In [ ]:
#Set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_A=torch.rand(4,5)

torch.manual_seed(RANDOM_SEED)
random_tensor_B=torch.rand(4,5)

random_tensor_A,random_tensor_B

(tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
         [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
         [0.9346, 0.5936, 0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739, 0.2666, 0.6274]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
         [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
         [0.9346, 0.5936, 0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739, 0.2666, 0.6274]]))